version: '3.8'

services:
  web:
    build: ./Website
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./Website:/var/www/html
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: server_management
      MYSQL_USER: server_admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - ./db_data:/var/lib/mysql
      - ./Website/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
